Add maintainers list
getsops/community pull request #15
Opened 2023-06-30 22:39 UTC by hiddeco

@getsops/maintainers please confirm and sign-off your information and affiliations, happy to update.

2023-06-30 23:07 UTC, onedr0p requested changes

2023-06-30 23:07 UTC, onedr0p commented on MAINTAINERS.md
> +- Devin Buhl, Individual <devin@buhl.casa> (GitHub: @onedr0p)
```suggestion
- Devin Buhl, Individual <devin@buhl.casa> (GitHub: @onedr0p, Slack: Devin Buhl)
```

2023-06-30 23:08 UTC, onedr0p approved these changes

2023-06-30 23:38 UTC, sabre1041 approved these changes
LGTM

2023-07-02 12:05 UTC, hiddeco commented
@devstein if you could sign-off on this, I can get the PR for the CNCF maintainers list going.

2023-07-02 12:24 UTC, devstein approved these changes
LGTM

2023-07-02 12:59 UTC, merged